//import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHome } from '@fortawesome/free-solid-svg-icons';
import { FaShoppingCart } from 'react-icons/fa'

const Header = () => {
        return (
        <>
            <Head>
                <title>SP ecommerce</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <section className='hero is-primary'>
                <div className='hero-body'>
                    <div className='columns'>
                        <div className='column'>
                            <p className='title'>
                            SP Book Box
                            </p>
                            <p className='subtitle'>
                            La base del éxito es la educación ...
                            </p>
                        </div>
                        <div className='column'></div>
                        <div className='column'></div>
                        <div className='column'>
                            <Link href='/home'>
                                <button className='button is-normal is-info is-light'>
                                    <span className='icon'>
                                    <FontAwesomeIcon icon={faHome} />
                                    </span>
                                </button> 
                            </Link>
                            <span>  </span>
                            <Link href='/home'>
                                <button className='button is-normal is-info is-light'>
                                    <span className='icon'>
                                    <FaShoppingCart />
                                    </span>
                                </button> 
                            </Link>
                            
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Header
